jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        submodules: recursive
      - script: |
          set -ex
          sudo add-apt-repository ppa:haxe/haxe3.4
          sudo apt-get update -qqy
          sudo apt-get install haxe -qqy
        displayName: Install Haxe
      - script: npm install
        displayName: Install libraries
      - script: npm run-script build
        displayName: Compile
      - script: npm run-script deploy
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), not(variables['System.PullRequest.PullRequestId']), variables['AWS_ACCESS_KEY_ID'])
        env:
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        displayName: Deploy
