tenant: haxefoundation
app: build-haxe-org
service: build-haxe-org
frameworkVersion: ">=1.44.0"

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    HXBUILDS_AWS_ACCESS_KEY_ID: ${ssm:HXBUILDS_AWS_ACCESS_KEY_ID}
    HXBUILDS_AWS_SECRET_ACCESS_KEY: ${ssm:HXBUILDS_AWS_SECRET_ACCESS_KEY}

functions:
  web:
    handler: index.handler
    events:
      - http:
          method: ANY
          path: '/'
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
